// This file is auto-generated by @hey-api/openapi-ts

export const CreateVendorRequestModelSchema = {
  required: ['name', 'description', 'pointOfContactName'],
  type: 'object',
  properties: {
    name: {
      maxLength: 50,
      minLength: 3,
      type: 'string',
    },
    description: {
      maxLength: 100,
      type: 'string',
    },
    pointOfContactName: {
      type: 'string',
    },
    pointOfContactEmail: {
      type: 'string',
    },
    pointOfContactPhone: {
      type: 'string',
    },
  },
} as const;

export const CreateVendorResponseModelSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    managerId: {
      type: 'string',
      format: 'uuid',
    },
    name: {
      type: ['null', 'string'],
    },
    description: {
      type: ['null', 'string'],
    },
    pointOfContact: {
      $ref: '#/components/schemas/VendorPointOfContact',
    },
  },
} as const;

export const VendorPointOfContactSchema = {
  required: ['id', 'name'],
  type: 'object',
  properties: {
    id: {
      type: 'string',
      format: 'uuid',
    },
    name: {
      type: 'string',
    },
    email: {
      type: ['null', 'string'],
    },
    phone: {
      type: ['null', 'string'],
    },
  },
} as const;
