// This file is auto-generated by @hey-api/openapi-ts
import { z } from 'zod';

export const zCreateVendorRequestModel = z.object({
  name: z.string().min(3).max(50),
  description: z.string().max(100),
  pointOfContactName: z.string(),
  pointOfContactEmail: z.optional(z.string()),
  pointOfContactPhone: z.optional(z.string()),
});

export const zVendorPointOfContact = z.object({
  id: z.uuid(),
  name: z.string(),
  email: z.optional(z.union([z.null(), z.string()])),
  phone: z.optional(z.union([z.null(), z.string()])),
});

export const zCreateVendorResponseModel = z.object({
  id: z.optional(z.uuid()),
  managerId: z.optional(z.uuid()),
  name: z.optional(z.union([z.null(), z.string()])),
  description: z.optional(z.union([z.null(), z.string()])),
  pointOfContact: z.optional(zVendorPointOfContact),
});

export const zPostApiSoftwareVendorsData = z.object({
  body: zCreateVendorRequestModel,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Created
 */
export const zPostApiSoftwareVendorsResponse = zCreateVendorResponseModel;
