// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetApiVendorsData,
  GetApiVendorsResponses,
  PostApiVendorsData,
  PostApiVendorsResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getApiVendors = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiVendorsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetApiVendorsResponses,
    unknown,
    ThrowOnError
  >({ url: '/api/vendors/', ...options });

/**
 * POST /vendors
 *
 * Allows a manager to add a new vendor to the system.
 */
export const postApiVendors = <ThrowOnError extends boolean = true>(
  options: Options<PostApiVendorsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostApiVendorsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/vendors/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
