// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://vendorsapi-dashboard.dev.localhost:15100/' | (string & {});
};

export type CreateVendorRequestModel = {
  name: string;
  description: string;
  pointOfContactName: string;
  pointOfContactEmail?: string;
  pointOfContactPhone?: string;
};

export type CreateVendorResponseModel = {
  id?: string;
  managerId?: string;
  name?: string;
  description?: string;
  pointOfContact?: VendorPointOfContact;
};

export type VendorListItem = {
  id?: string;
  name?: string;
  description?: string;
};

export type VendorPointOfContact = {
  id: string;
  name: string;
  email?: null | string;
  phone?: null | string;
};

export type GetApiVendorsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/vendors/';
};

export type GetApiVendorsResponses = {
  /**
   * OK
   */
  200: Array<VendorListItem>;
};

export type GetApiVendorsResponse =
  GetApiVendorsResponses[keyof GetApiVendorsResponses];

export type PostApiVendorsData = {
  body: CreateVendorRequestModel;
  path?: never;
  query?: never;
  url: '/api/vendors/';
};

export type PostApiVendorsResponses = {
  /**
   * Created
   */
  201: CreateVendorResponseModel;
};

export type PostApiVendorsResponse =
  PostApiVendorsResponses[keyof PostApiVendorsResponses];
