// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://localhost:12443/' | (string & {});
};

export type CreateVendorRequestModel = {
  name: string;
  description: string;
  pointOfContactName: string;
  pointOfContactEmail?: string;
  pointOfContactPhone?: string;
};

export type CreateVendorResponseModel = {
  id?: string;
  managerId?: string;
  name?: null | string;
  description?: null | string;
  pointOfContact?: VendorPointOfContact;
};

export type VendorPointOfContact = {
  id: string;
  name: string;
  email?: null | string;
  phone?: null | string;
};

export type PostApiSoftwareVendorsData = {
  body: CreateVendorRequestModel;
  path?: never;
  query?: never;
  url: '/api/software/vendors';
};

export type PostApiSoftwareVendorsResponses = {
  /**
   * Created
   */
  201: CreateVendorResponseModel;
};

export type PostApiSoftwareVendorsResponse =
  PostApiSoftwareVendorsResponses[keyof PostApiSoftwareVendorsResponses];
