
GET https://localhost:4000/orders


###

POST https://localhost:4000/orders
Content-Type: application/json 

{
    "customerName": "Ramya",
    "amount": 500
}


###

GET https://localhost:4000/openapi/v1.json

