// This file is auto-generated by @hey-api/openapi-ts
import { z } from 'zod';

export const zCreateVendorRequestModel = z.object({
  name: z.string().min(10).max(50),
  description: z.string().min(10).max(500),
  pointOfContactName: z.string(),
  pointOfContactEmail: z.optional(z.string()),
  pointOfContactPhone: z.optional(z.string()),
});

export const zVendorListItem = z.object({
  id: z.optional(z.uuid()),
  name: z.optional(z.string()),
  description: z.optional(z.string()),
});

export const zVendorPointOfContact = z.object({
  id: z.uuid(),
  name: z.string(),
  email: z.optional(z.union([z.null(), z.string()])),
  phone: z.optional(z.union([z.null(), z.string()])),
});

export const zCreateVendorResponseModel = z.object({
  id: z.optional(z.uuid()),
  managerId: z.optional(z.uuid()),
  name: z.optional(z.string()),
  description: z.optional(z.string()),
  pointOfContact: z.optional(zVendorPointOfContact),
});

export const zGetApiVendorsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * OK
 */
export const zGetApiVendorsResponse = z.array(zVendorListItem);

export const zPostApiVendorsData = z.object({
  body: zCreateVendorRequestModel,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Created
 */
export const zPostApiVendorsResponse = zCreateVendorResponseModel;
